{% set version = "1.3.2" %}

package:
  name: pynfft
  version: {{ version }}

source:
  fn: pyNFFT-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyNFFT/pyNFFT-{{ version }}.tar.gz
  md5: d2457a3f43839a8acce3295c60d5e692
  patches:
    # remove -malign-double compiler flag (for clang)
    - osx_flags.patch  # [osx]

build:
  number: 1001
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - numpy
    - nfft >=3.2,<3.6
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - nfft >=3.2,<3.6

test:
  imports:
    - pynfft
  commands:
    - python -c "from pynfft.nfft import NFFT; plan = NFFT(8, 8)"

about:
  home: https://github.com/ghisvail/pyNFFT.git
  license: GPLv3
  license_file: COPYING.txt
  summary: Pythonic bindings around the NFFT library

extra:
    recipe-maintainers:
      - ghisvail
      - grlee77
