appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: II26eQnDB6/aM/wmcwZbx/E06Q+xDFtmfzWMDJYAymHZzRnwNasuHhpss69UV+jD/QU7mtML7diCrBuAfAq4W9BsHknMUvvmhwW+m/eGGeFMdh354CeixmvjNIHWSbnn72XDT7Au/vXMX8W8VxscCQpctHgV+AppxojYhtz63LpkxgscBILlc4p7ofTbAW6TYN/Jvseb367gfxUJMTUoSZjEtSnaT1AcNLNxPwl0dNE3R8W1Pq445oihh76gYkzQp6V0M/WfmXTKSLYXV4zgU/q5qElN1/0+Hmwh2dE7h9cGiZ5UZCpLzmZLKggcKVLM3DYj5k001z1fH8xkOfwtTNtyjW6vYA8DnmhE4V1EgU2PGS8pfE8DCoKwhLQelFBNromi7A4e3z0zs9/41pKuiBiWBi9W0heQfXBH2cucasOCH7Rzncv6LD5iGasaiHwQFV4SGHhbqpqSqFJtkkB9+8TaQiqAcKux1N1bRErvNeYBLyIQErLn0hLbUwuaR0Q3e2Xy3tLLFBowyhLdznI4QqmfiqlXrBvigKdRxmPPcURsf8S5chn/8BoB0ln1QIxYBVJtdlwEdiE/bzA6CA4yijpnC2UMXLGV7QAaitrIiwdtFIQbXWBcwcP29GYBDguFtEqFaCVpvpH/BFGDdodgbp+WIKCTEY2pSKNIdZ6DPVY=}
